### ISSUE TITLE
"Enter" doesn't work on mobile, making task lists uneditable

### ISSUE THREAD

**Issue by Penguinjumper** [dylanonelson/sn-scratch-editor#7]
Hey, thanks for doing such a great job with this extension! :) 

Only problem I've noticed so far is that in the iOS App (and I think on Android, too, though I am not sure if I remember correctly) the following thing happens:

1 Want to start a Task List
2 Select the "Task Icon" button from toolbar
3 Task Icon appears
4 Type "do laundry"
5 Press Enter Key to start next task/new line of text
6 nothing happens, written text still goes in the line of the first task.

E.g.:

- [ ] Do LaundryClean room

Instead of 

- [ ] Do Laundry

- [ ] Clean room

Would be great if you could look into it. Thanks again! :)

**Comment by dylanonelson** [comment]
Hey, thanks for opening an issue! I'm glad you're enjoying the extension.

I have an Android phone, and I can't reproduce this bug there. I'll see if I can get my hands on an iOS device to test with, but it might take me a little while. Could you tell me what version of iOS you're running, and whether the same thing happens in mobile Safari?

**Comment by Penguinjumper** [comment]
Hey! Sorry for replying late, something didn't work with the mail notification!
I am using iOS 14.2 (18B92) on my phone, as well as iPadOS 14.2 18B92 on an iPad mini. Same issue on both devices. 
Since something seems to be wrong with my password (this is very weird as I use a password manager) I can't login in with safari right now, but I'll try again tomorrow and update you then!

**Comment by Penguinjumper** [comment]
So I tried using the web version in safari (https://dylanonelson.github.io/sn-scratch-editor/)
and found the same issue there. 

Also, apparently a similar issue happens with the quick formatting option (TT symbol, third from left).
This one however only malfunctions in the app, not in safari.

In general, the formatting bar seems a bit buggy on ios, sometimes I scroll up and it doesn't appear for example.

Thanks for checking this out again.

**Comment by dylanonelson** [comment]
Thanks for following up. I'll try to look into this soon!

**Comment by Penguinjumper** [comment]
Just wanted to subtly ask if you found out anything about this or if I could help by checking anything out in the ios app?

**Comment by dylanonelson** [comment]
Hey, thanks for the reminder on this. I had figured out how to reproduce it
but fixing it has been lingering on my todo list for a while. The good news
is I have a fix and I'll push it out tonight.

**Comment by Penguinjumper** [comment]
Amazing. You just made this the best SN-extension of all. Just by letting me have those checkboxes in normal notes.
Quickformat (TT Symbol) now works, as well!
I played around with it a little and found a few things still being buggy with iOS, and I'll open a new issue for those. But it's perfectly usable on iOS now!
